### ISSUE TITLE
login in failed

### ISSUE THREAD

**Issue by 944916121** [gywgithub/vue-vuetify-admin#9]
![QQ图片20211222104646](https://user-images.githubusercontent.com/44864812/147026762-a10c67da-cda5-4837-8e18-c43dd66d4252.png)

**Comment by 944916121** [comment]
![QQ图片20211222105108](https://user-images.githubusercontent.com/44864812/147027299-ac702568-a387-4f92-8224-ae4e4bb20458.png)

**Comment by gywgithub** [comment]
fix this issue in commit https://github.com/gywgithub/vue-vuetify-admin/commit/472dcf9cda4a6bd84c25248783288e2b2d2f8f16
